enum MyCacheKeys {
  isOnBoardingViewed,
  myEmail,
  myPassword,
  fullName,
  bio,
  address,
  phoneNumber,
  language,
  myToken,
  // Notifications Settings Keys
  jobSearchAlertSetting,
  jobApplicationUpdateSetting,
  jobApplicationRemindersSetting,
  jobsYouMayBeInterestedInSetting,
  jobSeekerUpdateSetting,
  showProfileSetting,
  allMessagesSetting,
  messageNudgesSetting,
  twoStepVerification, myID,
}